// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	PostID       int64              `json:"post_id"`
	UserID       int64              `json:"user_id"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	Price        int64              `json:"price"`
	Category     string             `json:"category"`
	PhotoUrl     string             `json:"photo_url"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	SessionID    pgtype.UUID        `json:"session_id"`
	UserID       int64              `json:"user_id"`
	RefreshToken string             `json:"refresh_token"`
	UserAgent    string             `json:"user_agent"`
	IpAddress    string             `json:"ip_address"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

type Shop struct {
	UserID       int64              `json:"user_id"`
	Name         pgtype.Text        `json:"name"`
	Description  pgtype.Text        `json:"description"`
	PhoneNumber  string             `json:"phone_number"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// social_id and email must be unique
type User struct {
	UserID int64 `json:"user_id"`
	// this field is for the unique id provided by google to identify a user
	SocialID     string             `json:"social_id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	Picture      string             `json:"picture"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	IsBlocked    bool               `json:"is_blocked"`
	IsAdmin      bool               `json:"is_admin"`
	LastSignInAt pgtype.Timestamptz `json:"last_sign_in_at"`
}
