// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// primary key is composed by user_id and social_id, both of those properties are unique
type User struct {
	UserID int64 `json:"user_id"`
	// this field is for the unique id provided by google to identify a user
	SocialID     string             `json:"social_id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	Picture      string             `json:"picture"`
	IsUserValid  bool               `json:"is_user_valid"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
}
