// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	PostID       int64              `json:"post_id"`
	UserID       int64              `json:"user_id"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	Price        int64              `json:"price"`
	Category     string             `json:"category"`
	PhotoUrl     string             `json:"photo_url"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Shop struct {
	UserID       int64              `json:"user_id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	WhatsappLink string             `json:"whatsapp_link"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// social_id and email must be unique
type User struct {
	UserID int64 `json:"user_id"`
	// this field is for the unique id provided by google to identify a user
	SocialID     string             `json:"social_id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	Picture      string             `json:"picture"`
	IsUserValid  bool               `json:"is_user_valid"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
}
