// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: posts.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :exec
INSERT INTO posts (user_id, title, description, price, category, photo_url) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreatePostParams struct {
	UserID      int64       `json:"user_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Price       int64       `json:"price"`
	Category    string      `json:"category"`
	PhotoUrl    string      `json:"photo_url"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.Exec(ctx, createPost,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.Category,
		arg.PhotoUrl,
	)
	return err
}

const getPosts = `-- name: GetPosts :many
SELECT u.username as "username", u.picture "userPicture", p.post_id as "postID", p.user_id as "userID", p.title, p.description, p.price, p.category, 
p.photo_url as "postPhotoURL", p.registered_at as "registeredAt" FROM posts p 
LEFT JOIN users u on u.user_id = p.user_id
`

type GetPostsRow struct {
	Username     pgtype.Text        `json:"username"`
	UserPicture  pgtype.Text        `json:"userPicture"`
	PostID       int64              `json:"postID"`
	UserID       int64              `json:"userID"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	Price        int64              `json:"price"`
	Category     string             `json:"category"`
	PostPhotoURL string             `json:"postPhotoURL"`
	RegisteredAt pgtype.Timestamptz `json:"registeredAt"`
}

func (q *Queries) GetPosts(ctx context.Context) ([]GetPostsRow, error) {
	rows, err := q.db.Query(ctx, getPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsRow
	for rows.Next() {
		var i GetPostsRow
		if err := rows.Scan(
			&i.Username,
			&i.UserPicture,
			&i.PostID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Category,
			&i.PostPhotoURL,
			&i.RegisteredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
