// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: posts.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (user_id, title, description, price, category, photo_url) 
VALUES ($1, $2, $3, $4, $5, $6) 
RETURNING user_id, post_id, title, description, price, category, photo_url, registered_at
`

type CreatePostParams struct {
	UserID      int64       `json:"user_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Price       int64       `json:"price"`
	Category    string      `json:"category"`
	PhotoUrl    string      `json:"photo_url"`
}

type CreatePostRow struct {
	UserID       int64              `json:"user_id"`
	PostID       int64              `json:"post_id"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	Price        int64              `json:"price"`
	Category     string             `json:"category"`
	PhotoUrl     string             `json:"photo_url"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (CreatePostRow, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.Category,
		arg.PhotoUrl,
	)
	var i CreatePostRow
	err := row.Scan(
		&i.UserID,
		&i.PostID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Category,
		&i.PhotoUrl,
		&i.RegisteredAt,
	)
	return i, err
}

const getFeedPosts = `-- name: GetFeedPosts :many
WITH scored_posts AS (
  SELECT
    u.username        AS "username",
    u.picture         AS "userPicture",
    p.post_id         AS "postID",
    p.user_id         AS "userID",
    p.title,
    p.description,
    p.price,
    p.category,
    p.photo_url       AS "postPhotoURL",
    p.registered_at   AS "registeredAt",
    s.phone_number    AS "phoneNumber",
    s.name            AS "shopName",
    s.description     AS "shopDescription",
    (('x' || substr(md5($3::text || p.post_id::text), 1, 8))::bit(32)::bigint & 2147483647)::float8 / 2147483647.0
      * POW(0.5, EXTRACT(EPOCH FROM NOW() - p.registered_at) / 604800.0) AS score
  FROM posts p
  LEFT JOIN users u ON u.user_id = p.user_id
  LEFT JOIN shop s ON s.user_id = p.user_id
  WHERE ($4::text = '' OR p.category ILIKE $4::text)
  AND (
    $5::text = ''
    OR p.title       ILIKE '%' || $5::text || '%'
    OR p.description ILIKE '%' || $5::text || '%'
    OR u.username    ILIKE '%' || $5::text || '%'
    OR s.name        ILIKE '%' || $5::text || '%'
  )
)
SELECT "username", "userPicture", "postID", "userID", title, description, price, category,
       "postPhotoURL", "registeredAt", "phoneNumber", "shopName", "shopDescription", score
FROM scored_posts
WHERE ($1::float8 = 0 AND $2::bigint = 0)
   OR score < $1::float8
   OR (score = $1::float8 AND "postID" > $2::bigint)
ORDER BY score DESC, "postID" ASC
LIMIT 9
`

type GetFeedPostsParams struct {
	CursorScore  float64 `json:"cursor_score"`
	CursorPostID int64   `json:"cursor_post_id"`
	Seed         string  `json:"seed"`
	Category     string  `json:"category"`
	Search       string  `json:"search"`
}

type GetFeedPostsRow struct {
	Username        pgtype.Text        `json:"username"`
	UserPicture     pgtype.Text        `json:"userPicture"`
	PostID          int64              `json:"postID"`
	UserID          int64              `json:"userID"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Price           int64              `json:"price"`
	Category        string             `json:"category"`
	PostPhotoURL    string             `json:"postPhotoURL"`
	RegisteredAt    pgtype.Timestamptz `json:"registeredAt"`
	PhoneNumber     pgtype.Text        `json:"phoneNumber"`
	ShopName        pgtype.Text        `json:"shopName"`
	ShopDescription pgtype.Text        `json:"shopDescription"`
	Score           int32              `json:"score"`
}

// Returns posts ordered by a deterministic recency-biased score.
// Uses md5(seed || post_id) for deterministic pseudo-random ordering — pure function,
// no connection state mutation (unlike setseed).
// Accepts a text seed generated client-side per browsing session.
// score = md5_hash_as_float × 0.5^(age_in_weeks), half-life = 7 days.
// Cursor-based pagination: pass cursor_score=0 and cursor_post_id=0 for the first page.
// For subsequent pages, pass the score and postID of the last post from the previous page.
// Pass an empty string for category/search to skip those filters.
func (q *Queries) GetFeedPosts(ctx context.Context, arg GetFeedPostsParams) ([]GetFeedPostsRow, error) {
	rows, err := q.db.Query(ctx, getFeedPosts,
		arg.CursorScore,
		arg.CursorPostID,
		arg.Seed,
		arg.Category,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedPostsRow
	for rows.Next() {
		var i GetFeedPostsRow
		if err := rows.Scan(
			&i.Username,
			&i.UserPicture,
			&i.PostID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Category,
			&i.PostPhotoURL,
			&i.RegisteredAt,
			&i.PhoneNumber,
			&i.ShopName,
			&i.ShopDescription,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPosts = `-- name: GetPosts :many
SELECT u.username as "username", u.picture "userPicture", p.post_id as "postID", p.user_id as "userID", p.title, p.description, p.price, p.category, 
p.photo_url as "postPhotoURL", p.registered_at as "registeredAt" FROM posts p 
LEFT JOIN users u on u.user_id = p.user_id
`

type GetPostsRow struct {
	Username     pgtype.Text        `json:"username"`
	UserPicture  pgtype.Text        `json:"userPicture"`
	PostID       int64              `json:"postID"`
	UserID       int64              `json:"userID"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	Price        int64              `json:"price"`
	Category     string             `json:"category"`
	PostPhotoURL string             `json:"postPhotoURL"`
	RegisteredAt pgtype.Timestamptz `json:"registeredAt"`
}

func (q *Queries) GetPosts(ctx context.Context) ([]GetPostsRow, error) {
	rows, err := q.db.Query(ctx, getPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsRow
	for rows.Next() {
		var i GetPostsRow
		if err := rows.Scan(
			&i.Username,
			&i.UserPicture,
			&i.PostID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Category,
			&i.PostPhotoURL,
			&i.RegisteredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
