// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repo

import (
	"context"
)

type Querier interface {
	CreatePost(ctx context.Context, arg CreatePostParams) (CreatePostRow, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateShop(ctx context.Context, arg CreateShopParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllSessionsByUserID(ctx context.Context, userID int64) error
	DeleteSession(ctx context.Context, refreshToken string) error
	// Returns posts ordered by a deterministic recency-biased score.
	// Uses md5(seed || post_id) for deterministic pseudo-random ordering — pure function,
	// no connection state mutation (unlike setseed).
	// Accepts a text seed generated client-side per browsing session.
	// score = md5_hash_as_float × 0.5^(age_in_weeks), half-life = 7 days.
	// Uses session_time (client-provided Unix epoch seconds) instead of NOW() so that
	// scores are stable across all page requests in the same session — required for
	// correct cursor-based pagination (time-varying scores break cursor boundaries).
	// Cursor-based pagination: pass cursor_score=0 and cursor_post_id=0 for the first page.
	// For subsequent pages, pass the score and postID of the last post from the previous page.
	// Pass an empty string for category/search to skip those filters.
	GetFeedPosts(ctx context.Context, arg GetFeedPostsParams) ([]GetFeedPostsRow, error)
	GetPosts(ctx context.Context) ([]GetPostsRow, error)
	GetSessionByRefreshToken(ctx context.Context, refreshToken string) (Session, error)
	GetUserByID(ctx context.Context, userID int64) (GetUserByIDRow, error)
	GetUserBySocialID(ctx context.Context, socialID string) (User, error)
	UpdateSessionToken(ctx context.Context, arg UpdateSessionTokenParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
