// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: sessions.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, refresh_token, user_agent, ip_address, expires_at) 
VALUES ($1, $2, $3, $4, $5)
RETURNING session_id, user_id, refresh_token, user_agent, ip_address, created_at, expires_at
`

type CreateSessionParams struct {
	UserID       int64              `json:"user_id"`
	RefreshToken string             `json:"refresh_token"`
	UserAgent    string             `json:"user_agent"`
	IpAddress    string             `json:"ip_address"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshToken,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteAllSessionsByUserID = `-- name: DeleteAllSessionsByUserID :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteAllSessionsByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteAllSessionsByUserID, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE refresh_token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, refreshToken string) error {
	_, err := q.db.Exec(ctx, deleteSession, refreshToken)
	return err
}

const getSessionByRefreshToken = `-- name: GetSessionByRefreshToken :one
SELECT session_id, user_id, refresh_token, user_agent, ip_address, created_at, expires_at FROM sessions WHERE refresh_token = $1
`

func (q *Queries) GetSessionByRefreshToken(ctx context.Context, refreshToken string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshToken, refreshToken)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateSessionToken = `-- name: UpdateSessionToken :exec
UPDATE sessions SET refresh_token = $1, expires_at = $2, updated_at = now() WHERE session_id = $3
`

type UpdateSessionTokenParams struct {
	RefreshToken string             `json:"refresh_token"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	SessionID    pgtype.UUID        `json:"session_id"`
}

func (q *Queries) UpdateSessionToken(ctx context.Context, arg UpdateSessionTokenParams) error {
	_, err := q.db.Exec(ctx, updateSessionToken, arg.RefreshToken, arg.ExpiresAt, arg.SessionID)
	return err
}
