// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: shop.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShop = `-- name: CreateShop :exec
INSERT INTO shop (user_id, name, description, whatsapp_link) VALUES ($1, $2, $3, $4)
`

type CreateShopParams struct {
	UserID       int64       `json:"user_id"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	WhatsappLink string      `json:"whatsapp_link"`
}

func (q *Queries) CreateShop(ctx context.Context, arg CreateShopParams) error {
	_, err := q.db.Exec(ctx, createShop,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.WhatsappLink,
	)
	return err
}
