// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: shop.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShop = `-- name: CreateShop :exec
INSERT INTO shop (user_id, name, description, phone_number) 
VALUES ($1, $2, $3, $4) 
ON CONFLICT (user_id) DO 
UPDATE SET 
name = $2,
description = $3,
phone_number = $4,
updated_at = now()
`

type CreateShopParams struct {
	UserID      int64       `json:"user_id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	PhoneNumber string      `json:"phone_number"`
}

func (q *Queries) CreateShop(ctx context.Context, arg CreateShopParams) error {
	_, err := q.db.Exec(ctx, createShop,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.PhoneNumber,
	)
	return err
}
