// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (social_id, email, username, picture) VALUES ($1, $2, $3, $4) RETURNING user_id, social_id, email, username, picture, registered_at, is_blocked, is_admin, last_sign_in_at
`

type CreateUserParams struct {
	SocialID string `json:"social_id"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Picture  string `json:"picture"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.SocialID,
		arg.Email,
		arg.Username,
		arg.Picture,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.SocialID,
		&i.Email,
		&i.Username,
		&i.Picture,
		&i.RegisteredAt,
		&i.IsBlocked,
		&i.IsAdmin,
		&i.LastSignInAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT users.user_id as "userID", users.email, users.username, users.picture, users.is_blocked as "isBlocked", shop."name" as "shopName", shop.description as "shopDescription", shop.phone_number as "phoneNumber"
FROM users 
left join shop on users.user_id = shop.user_id
WHERE users.user_id = $1
`

type GetUserByIDRow struct {
	UserID          int64       `json:"userID"`
	Email           string      `json:"email"`
	Username        string      `json:"username"`
	Picture         string      `json:"picture"`
	IsBlocked       bool        `json:"isBlocked"`
	ShopName        pgtype.Text `json:"shopName"`
	ShopDescription pgtype.Text `json:"shopDescription"`
	PhoneNumber     pgtype.Text `json:"phoneNumber"`
}

func (q *Queries) GetUserByID(ctx context.Context, userID int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Username,
		&i.Picture,
		&i.IsBlocked,
		&i.ShopName,
		&i.ShopDescription,
		&i.PhoneNumber,
	)
	return i, err
}

const getUserBySocialID = `-- name: GetUserBySocialID :one
SELECT user_id, social_id, email, username, picture, registered_at, is_blocked, is_admin, last_sign_in_at FROM users WHERE social_id = $1
`

func (q *Queries) GetUserBySocialID(ctx context.Context, socialID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySocialID, socialID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.SocialID,
		&i.Email,
		&i.Username,
		&i.Picture,
		&i.RegisteredAt,
		&i.IsBlocked,
		&i.IsAdmin,
		&i.LastSignInAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET email =  $1, username = $2, picture = $3 WHERE user_id = $4 RETURNING user_id, social_id, email, username, picture, registered_at, is_blocked, is_admin, last_sign_in_at
`

type UpdateUserParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Picture  string `json:"picture"`
	UserID   int64  `json:"user_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Email,
		arg.Username,
		arg.Picture,
		arg.UserID,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.SocialID,
		&i.Email,
		&i.Username,
		&i.Picture,
		&i.RegisteredAt,
		&i.IsBlocked,
		&i.IsAdmin,
		&i.LastSignInAt,
	)
	return i, err
}
