// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users.sql

package repo

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (social_id, email, username, picture) VALUES ($1, $2, $3, $4)
`

type CreateUserParams struct {
	SocialID string `json:"social_id"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Picture  string `json:"picture"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.SocialID,
		arg.Email,
		arg.Username,
		arg.Picture,
	)
	return err
}
